### ISSUE TITLE
gulp / browserSync question

### ISSUE THREAD

**Issue by s10wen** [zackphilipps/scratch-theme#12]
I've tried `gulp watch` and that compiles the Sass => CSS.

And `gulp browserSync` and that spins up `http://localhost:3000/~username/sitename/`.

But it's not auto refreshing, I've updated the `gulpfile.js`:

```
proxy: 'localhost/~username/sitename/',
```

Is there a step I'm missing?

**Comment by zoephilipps** [comment]
@s10wen Hi! Have you tried just `gulp`? `gulp` should start both `browserSync` and `watch`.

**Comment by s10wen** [comment]
@zackphilipps ah cheers! It looks like this does start both up, but looks like I'm getting a permission issue:

```
[09:44:04] Starting 'styles'...
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: EPERM: operation not permitted, chmod ' … scratch-theme/website/assets/css/master.css'
```

I tried to `chmod` the file / directory, but no luck.

`sudo gulp` seems to do the job, but would be nice to know what the issue is if you have any ideas?

**Comment by zoephilipps** [comment]
@s10wen Did you by chance install any of your `npm` packages with `sudo`?

**Comment by s10wen** [comment]
@zackphilipps no, I try to avoid `sudo` whenever possible

**Comment by zoephilipps** [comment]
@s10wen what version of node are you running? Run `node -v` and `npm -v` and let me know what you get.

**Comment by s10wen** [comment]
```
node -v
v9.4.0

npm -v
5.7.1
```

**Comment by zoephilipps** [comment]
@s10wen Ah, I think it's time for these `package.json` files to be updated for newer node versions. I have no idea how much work that would be, and I don't plan on doing it in the foreseeable future. If you want to take a crack at a PR, I'd welcome it. In the meantime, I'd suggest using [nvm](https://github.com/creationix/nvm) and grabbing node v6. That's what I'm running currently and gulp works fine.

**Comment by s10wen** [comment]
After much faffing around, I think I've fixed it. I'm not sure how, but I think some permissions got changed. So I updated them running the following commands from the root WordPress path:

```
sudo find . -type f -exec chmod 664 {} +
sudo find . -type d -exec chmod 775 {} +
```
(Useful article I found: https://www.smashingmagazine.com/2014/05/proper-wordpress-filesystem-permissions-ownerships/)

Then also noticed in:
`/private/etc/apache2/httpd.conf` > line 181

I had:
```
User _www
Group _www
```

So updated to:
```
User s10wen
Group staff
```

And then restarted Apache:
```
sudo apachectl -k restart
```

**Comment by zoephilipps** [comment]
@s10wen Ah, so it was \*actually\* a classic permissions/ownership issue. Glad you got it resolved. Btw, out of curiosity, what are you using as your host?

**Comment by s10wen** [comment]
This was local, OS X.

Yeah, looks like a script I had ran, had done some unwanted things.
