### ISSUE TITLE
Cannot use hero block more than once on a page

### ISSUE THREAD

**Issue by brigleb** [zackphilipps/scratch-theme#9]
Perhaps this is a PEBCAK here, but when I try to use more than one hero block on a page, I get an error.

`Fatal error: Cannot redeclare scratch_bg_position()` ...

It *seems* as though moving the function declaration from `layout-hero_unit.php` into `page-layouts.php` fixes this, but I'm not sure if that's the best solution. For instance, perhaps it should be incorporated into `functions.php` or somewhere similar?

**Comment by zoephilipps** [comment]
@brigleb nope, not your problem, haha. I'll move that to one of the core files.

**Comment by brigleb** [comment]
Actually, when I did that just now, I ran into some *other* odd errors.

I then instead tried just checking if the function existed, by wrapping it with this kind of code (in `layout-hero_unit.php`):

`if ( ! function_exists( 'scratch_bg_position' ) ) { ... }`

As far as I can tell, this fixes the problem and introduces no others!

**Comment by zoephilipps** [comment]
@brigleb nice, great minds think alike!
